#!/bin/bash
clear
rm ~/x

sleep 1
echo "Install Box86 version."
echo "Install WoW64 version."

if [ "$choice" = "1"]; then
curl -L https://githubuscontent.com/ShephardOS9/BoxWine/main/wow64.sh
 fi
if [ "$choice" = "1"]; then
curl -L https://githubuscontent.com/ShephardOS9/BoxWine/main/box86.sh
 fi
